``` {r cars}
library(ggplot2)
library(ggsignif)
library(gridExtra)
```

## ==== loading data ==== ##
```{r cars}
atlas <- 'Amygdala'   # choices = c('HarvardOxford_Cortical', 'HarvardOxford_Subcortical', 'Cerebellum', 'ReinforcementLearning', 'Amygdala')
year <- 'after1y'    # choices = c('after1y', 'after2y') 
cluster_save_dir = "/Users/wangheehwan/Desktop/CNN_for_BMI/paper/data/clustering/cluster_label/sensitivity/case_control"
pval_save_dir = "/Users/wangheehwan/Desktop/CNN_for_BMI/paper/data/clustering/ttest/sensitivity/case_control"
img_save_dir = "/Users/wangheehwan/Desktop/CNN_for_BMI/paper/data/clustering/ttest/sensitivity/case_control"



pheno_case <- read.csv(paste0(cluster_save_dir, '/', atlas, '/', year, '_case_cluster.csv'))
pheno_delta_case <- read.csv(paste0(cluster_save_dir, '/', atlas, '/', year, '_case_cluster_delta.csv'))
pheno_control <- read.csv(paste0(cluster_save_dir, '/', atlas, '/', year, '_control_cluster.csv'))
pheno_delta_control <- read.csv(paste0(cluster_save_dir, '/', atlas, '/', year, '_control_cluster_delta.csv'))
```


## ==== Demographic  ==== ##
```{r cars}
title = 'Demographic'
#target_list = c('BMI_sds_baseline', 'birth_weight', 'child_age', 'high_educ', 'rh_income1')
target_list = c('birth_weight', 'child_age', 'high_educ', 'income')

# load data
pval_df <- read.csv(paste0(pval_save_dir, '/', atlas, '/', title, '_', year, '_ttest.csv'))

# Create a grid for subplots
p <- list()
count <- 1

# Loop over target variables
for (target in target_list) {
  # Data preprocess
  # Control
  df_control <- na.omit(pheno_control[, target])
  df_control <- data.frame(target = df_control, cluster_label = 'control')
  
  # Case
  df_case <- na.omit(pheno_case[, c('cluster_label', target)])
  colnames(df_case) <- c('cluster_label', 'target')
  df_case$cluster_label <- paste0('cluster', df_case$cluster_label)
  
  # Combine data
  df_all <- rbind(df_control, df_case)
  
  # P-value annotation
  
  pval_adj <- pval_df[pval_df$variables == target, ]$p_value_BONF
  comparison <- list()
  annotation <- c()
  
  for (i in 1:length(pval_adj)) {
    if (pval_adj[i] < 0.05) {
      comparison <- c(comparison, list(strsplit(pval_df[pval_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '*')
    }else if(pval_adj[i] < 0.005) {
      comparison <- c(comparison, list(strsplit(pval_df[pval_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '**')
    }else if(pval_adj[i] < 0.0005) {
      comparison <- c(comparison, list(strsplit(pval_df[pval_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '***')
    }
  }
  
  
  # Generate the boxplot with significance annotations
  p[[count]] <- ggplot(df_all, aes(x = cluster_label, y = target, fill=cluster_label)) +
                geom_violin() +
                scale_fill_brewer(palette = "Blues") +
                geom_boxplot(outlier.shape = NA, width = .05, fill='white') +
                stat_summary(fun=match.fun(mean), geom="point", colour="red", alpha=0.7) +
                geom_signif(annotation=annotation,
                            comparisons = comparison, 
                            map_signif_level = TRUE, 
                            step_increase = 0.12,
                            ) + 
                scale_x_discrete(limits =  c('control','cluster0', 'cluster1')) +
                ylab(target) +
                #ggtitle(target) + 
                
                theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  count <- count + 1
  # Print the subplot
}
plt <- do.call(grid.arrange, p)
ggsave(paste0(img_save_dir, '/', atlas, '/', 'plot','/',title, '_', year, '_ttest.png'), plt, width = 12, height = 10, limitsize = FALSE,dpi=700)
```


## ==== Polygenic Score ==== ##
```{r cars}
title = 'PolygenicScore'
target_list = c('bmieur4', 'edauto', 'insomniaeur6', 'snoringeur1', 'adhdeur6', 'ptsdeur4', 'bipauto',  'mddeur6',  'anxietyauto', 'ocdauto', 'worryauto')

# load data
pval_df <- read.csv(paste0(pval_save_dir, '/', atlas, '/', title, '_', year, '_ttest.csv'))

# Create a grid for subplots
p <- list()
count <- 1

# Loop over target variables
for (target in target_list) {
  # Data preprocess
  # Control
  df_control <- na.omit(pheno_control[, target])
  df_control <- data.frame(target = df_control, cluster_label = 'control')
  
  # Case
  df_case <- na.omit(pheno_case[, c('cluster_label', target)])
  colnames(df_case) <- c('cluster_label', 'target')
  df_case$cluster_label <- paste0('cluster', df_case$cluster_label)
  
  # Combine data
  df_all <- rbind(df_control, df_case)
  
  # P-value annotation
  
  pval_adj <- pval_df[pval_df$variables == target, ]$p_value_BONF
  comparison <- list()
  annotation <- c()
  
  for (i in 1:length(pval_adj)) {
    if (pval_adj[i] < 0.05) {
      comparison <- c(comparison, list(strsplit(pval_df[pval_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '*')
    }else if(pval_adj[i] < 0.005) {
      comparison <- c(comparison, list(strsplit(pval_df[pval_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '**')
    }else if(pval_adj[i] < 0.0005) {
      comparison <- c(comparison, list(strsplit(pval_df[pval_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '***')
    }
  }
  
  
  # Generate the boxplot with significance annotations
  p[[count]] <- ggplot(df_all, aes(x = cluster_label, y = target, fill=cluster_label)) +
                geom_violin() +
                scale_fill_brewer(palette = "Blues") +
                geom_boxplot(outlier.shape = NA, width = .05, fill='white') +
                stat_summary(fun=match.fun(mean), geom="point", colour="red", alpha=0.7) +
                geom_signif(annotation=annotation,
                            comparisons = comparison, 
                            map_signif_level = TRUE, 
                            step_increase = 0.12,
                            ) + 
                scale_x_discrete(limits =  c('control','cluster0', 'cluster1')) +
                ylab(target) +
                #ggtitle(target) + 
                
                theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  count <- count + 1
  # Print the subplot
}
plt <- do.call(grid.arrange, p)
ggsave(paste0(img_save_dir, '/', atlas, '/', 'plot','/',title, '_', year, '_ttest.png'), plt, width = 18, height = 15, limitsize = FALSE,dpi=700)

```

## ==== Sleep Disturbance ==== ##
```{r cars}
title = 'SleepDisturbance'
target_list = c('sleep_disturb_dims', 'sleep_disturb_sbd', 'sleep_disturb_da', 'sleep_disturb_swtd', 'sleep_disturb_does', 'sleep_disturb_shy', 'sleep_disturb_total')
pval_df <- read.csv(paste0(pval_save_dir, '/', atlas, '/', title, '_', year, '_ttest.csv'))
pval_delta_df = read.csv(paste0(pval_save_dir, '/', atlas, '/', title, '_', year, '_delta_ttest.csv'))

### Raw score
# Create a grid for subplots
p <- list()
count <- 1

# Loop over target variables
for (target in target_list) {
  # Data preprocess
  # Control
  df_control <- na.omit(pheno_control[, target])
  df_control <- data.frame(target = df_control, cluster_label = 'control')
  
  # Case
  df_case <- na.omit(pheno_case[, c('cluster_label', target)])
  colnames(df_case) <- c('cluster_label', 'target')
  df_case$cluster_label <- paste0('cluster', df_case$cluster_label)
  
  # Combine data
  df_all <- rbind(df_control, df_case)
  
  # P-value annotation
  
  pval_adj <- pval_df[pval_df$variables == target, ]$p_value_BONF
  comparison <- list()
  annotation <- c()
  
  for (i in 1:length(pval_adj)) {
    if (pval_adj[i] < 0.05) {
      comparison <- c(comparison, list(strsplit(pval_df[pval_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '*')
    }else if(pval_adj[i] < 0.005) {
      comparison <- c(comparison, list(strsplit(pval_df[pval_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '**')
    }else if(pval_adj[i] < 0.0005) {
      comparison <- c(comparison, list(strsplit(pval_df[pval_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '***')
    }
  }
  
  
  # Generate the boxplot with significance annotations
  p[[count]] <- ggplot(df_all, aes(x = cluster_label, y = target, fill=cluster_label)) +
                geom_violin() +
                scale_fill_brewer(palette = "Blues") +
                geom_boxplot(outlier.shape = NA, width = .05, fill='white') +
                stat_summary(fun=match.fun(mean), geom="point", colour="red", alpha=0.7) +
                geom_signif(annotation=annotation,
                            comparisons = comparison, 
                            map_signif_level = TRUE, 
                            step_increase = 0.12,
                            ) + 
                scale_x_discrete(limits =  c('control','cluster0', 'cluster1')) +
                ylab(target) +
                #ggtitle(target) + 
                
                theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  count <- count + 1
  # Print the subplot
}
plt <- do.call(grid.arrange, p)
ggsave(paste0(img_save_dir, '/', atlas, '/', 'plot','/',title, '_', year, '_ttest.png'), plt, width = 18, height = 15, limitsize = FALSE,dpi=700)


### Delta score
# Create a grid for subplots
p <- list()
count <- 1

# Loop over target variables
for (target in target_list) {
  # Data preprocess
  # Control
  df_control_baseline <- na.omit(pheno_delta_control[pheno_delta_control$eventname=='baseline_year_1_arm_1', c('subjectkey',target)])
  colnames(df_control_baseline) <- c('subjectkey', 'target_baseline')
  if (year == 'after1y'){
    df_control_followup <- na.omit(pheno_delta_control[pheno_delta_control$eventname=='1_year_follow_up_y_arm_1', c('subjectkey', target)])
  } else if (year == 'after2y'){
    df_control_followup <- na.omit(pheno_delta_control[pheno_delta_control$eventname=='2_year_follow_up_y_arm_1', c('subjectkey', target)])
  }
  colnames(df_control_followup ) <- c('subjectkey', 'target_followup')
  df_control_delta <- merge(df_control_baseline, df_control_followup, by='subjectkey')
  df_control_delta[, 'target'] <- df_control_delta[, 'target_followup'] - df_control_delta[,'target_baseline']
  df_control <- data.frame(target = df_control_delta[, 'target'], cluster_label = 'control')
  
  # Case
  df_case_baseline <- na.omit(pheno_delta_case[pheno_delta_case$eventname=='baseline_year_1_arm_1', c('subjectkey', target)])
  colnames(df_case_baseline) <- c('subjectkey','target_baseline')
  if (year == 'after1y'){
    df_case_followup <- na.omit(pheno_delta_case[pheno_delta_case$eventname=='1_year_follow_up_y_arm_1', c('subjectkey', 'cluster_label', target)])
  } else if (year == 'after2y'){
    df_case_followup <- na.omit(pheno_delta_case[pheno_delta_case$eventname=='2_year_follow_up_y_arm_1', c('subjectkey', 'cluster_label', target)])
  }
  colnames(df_case_followup) <- c('subjectkey', 'cluster_label', 'target_followup')
  df_case_delta <- merge(df_case_baseline, df_case_followup, by='subjectkey')
  df_case_delta[, 'target'] <-  df_case_delta[, 'target_followup'] - df_case_delta[,'target_baseline']
  df_case = df_case_delta[, c('target', 'cluster_label')]
  df_case$cluster_label <- paste0('cluster', df_case$cluster_label)
  
  # Combine data
  df_all <- rbind(df_control, df_case)
  
  # P-value annotation
  
  pval_adj <- pval_delta_df[pval_delta_df$variables == target, ]$p_value_BONF
  comparison <- list()
  annotation <- c()
  
  for (i in 1:length(pval_adj)) {
    if (pval_adj[i] < 0.05) {
      comparison <- c(comparison, list(strsplit(pval_delta_df[pval_delta_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '*')
    }else if(pval_adj[i] < 0.005) {
      comparison <- c(comparison, list(strsplit(pval_delta_df[pval_delta_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '**')
    }else if(pval_adj[i] < 0.0005) {
      comparison <- c(comparison, list(strsplit(pval_delta_df[pval_delta_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '***')
    }
  }
  
  
  # Generate the boxplot with significance annotations
  p[[count]] <- ggplot(df_all, aes(x = cluster_label, y = target, fill=cluster_label)) +
                geom_violin() +
                scale_fill_brewer(palette = "Blues") +
                geom_boxplot(outlier.shape = NA, width = .05, fill='white') +
                stat_summary(fun=match.fun(mean), geom="point", colour="red", alpha=0.7) +
                geom_signif(annotation=annotation,
                            comparisons = comparison, 
                            map_signif_level = TRUE, 
                            step_increase = 0.12,
                            ) + 
                scale_x_discrete(limits =  c('control','cluster0', 'cluster1')) +
                ylab(target) +
                
                theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  count <- count + 1
  # Print the subplot
}
plt <- do.call(grid.arrange, p)
ggsave(paste0(img_save_dir, '/', atlas, '/', 'plot','/',title, '_', year, '_delta_ttest.png'), plt, width = 18, height = 15, limitsize = FALSE,dpi=700)

```



## ==== CBCL Syndrome scale==== ##
```{r cars}
title = 'CBCLSyndrome'
target_list = c("cbcl_anxiety", "cbcl_withdep","cbcl_somatic","cbcl_social","cbcl_thought","cbcl_attention","cbcl_rulebreak","cbcl_aggressive","cbcl_internal","cbcl_external","cbcl_totprob")
pval_df <- read.csv(paste0(pval_save_dir, '/', atlas, '/', title, '_', year, '_ttest.csv'))
pval_delta_df = read.csv(paste0(pval_save_dir, '/', atlas, '/', title, '_', year, '_delta_ttest.csv'))

### Raw score
# Create a grid for subplots
p <- list()
count <- 1

# Loop over target variables
for (target in target_list) {
  # Data preprocess
  # Control
  df_control <- na.omit(pheno_control[, target])
  df_control <- data.frame(target = df_control, cluster_label = 'control')
  
  # Case
  df_case <- na.omit(pheno_case[, c('cluster_label', target)])
  colnames(df_case) <- c('cluster_label', 'target')
  df_case$cluster_label <- paste0('cluster', df_case$cluster_label)
  
  # Combine data
  df_all <- rbind(df_control, df_case)
  
  # P-value annotation
  
  pval_adj <- pval_df[pval_df$variables == target, ]$p_value_BONF
  comparison <- list()
  annotation <- c()
  
  for (i in 1:length(pval_adj)) {
    if (pval_adj[i] < 0.05) {
      comparison <- c(comparison, list(strsplit(pval_df[pval_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '*')
    }else if(pval_adj[i] < 0.005) {
      comparison <- c(comparison, list(strsplit(pval_df[pval_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '**')
    }else if(pval_adj[i] < 0.0005) {
      comparison <- c(comparison, list(strsplit(pval_df[pval_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '***')
    }
  }
  
  
  # Generate the boxplot with significance annotations
  p[[count]] <- ggplot(df_all, aes(x = cluster_label, y = target, fill=cluster_label)) +
                geom_violin() +
                scale_fill_brewer(palette = "Blues") +
                geom_boxplot(outlier.shape = NA, width = .05, fill='white') +
                stat_summary(fun=match.fun(mean), geom="point", colour="red", alpha=0.7) +
                geom_signif(annotation=annotation,
                            comparisons = comparison, 
                            map_signif_level = TRUE, 
                            step_increase = 0.12,
                            ) + 
                scale_x_discrete(limits =  c('control','cluster0', 'cluster1')) +
                ylab(target) +
                
                theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  count <- count + 1
  # Print the subplot
}
plt <- do.call(grid.arrange, p)
ggsave(paste0(img_save_dir, '/', atlas, '/', 'plot','/',title, '_', year, '_ttest.png'), plt, width = 18, height = 15, limitsize = FALSE,dpi=700)


### Delta score
# Create a grid for subplots
p <- list()
count <- 1

# Loop over target variables
for (target in target_list) {
  # Data preprocess
  # Control
  df_control_baseline <- na.omit(pheno_delta_control[pheno_delta_control$eventname=='baseline_year_1_arm_1', c('subjectkey',target)])
  colnames(df_control_baseline) <- c('subjectkey', 'target_baseline')
  if (year == 'after1y'){
    df_control_followup <- na.omit(pheno_delta_control[pheno_delta_control$eventname=='1_year_follow_up_y_arm_1', c('subjectkey', target)])
  } else if (year == 'after2y'){
    df_control_followup <- na.omit(pheno_delta_control[pheno_delta_control$eventname=='2_year_follow_up_y_arm_1', c('subjectkey', target)])
  }
  colnames(df_control_followup ) <- c('subjectkey', 'target_followup')
  df_control_delta <- merge(df_control_baseline, df_control_followup, by='subjectkey')
  df_control_delta[, 'target'] <- df_control_delta[, 'target_followup'] - df_control_delta[,'target_baseline']
  df_control <- data.frame(target = df_control_delta[, 'target'], cluster_label = 'control')
  
  # Case
  df_case_baseline <- na.omit(pheno_delta_case[pheno_delta_case$eventname=='baseline_year_1_arm_1', c('subjectkey', target)])
  colnames(df_case_baseline) <- c('subjectkey','target_baseline')
  if (year == 'after1y'){
    df_case_followup <- na.omit(pheno_delta_case[pheno_delta_case$eventname=='1_year_follow_up_y_arm_1', c('subjectkey', 'cluster_label', target)])
  } else if (year == 'after2y'){
    df_case_followup <- na.omit(pheno_delta_case[pheno_delta_case$eventname=='2_year_follow_up_y_arm_1', c('subjectkey', 'cluster_label', target)])
  }
  colnames(df_case_followup) <- c('subjectkey', 'cluster_label', 'target_followup')
  df_case_delta <- merge(df_case_baseline, df_case_followup, by='subjectkey')
  df_case_delta[, 'target'] <-  df_case_delta[, 'target_followup'] - df_case_delta[,'target_baseline']
  df_case = df_case_delta[, c('target', 'cluster_label')]
  df_case$cluster_label <- paste0('cluster', df_case$cluster_label)

  
  # Combine data
  df_all <- rbind(df_control, df_case)
  
  # P-value annotation
  
  pval_adj <- pval_delta_df[pval_delta_df$variables == target, ]$p_value_BONF
  comparison <- list()
  annotation <- c()
  
  for (i in 1:length(pval_adj)) {
    if (pval_adj[i] < 0.05) {
      comparison <- c(comparison, list(strsplit(pval_delta_df[pval_delta_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '*')
    }else if(pval_adj[i] < 0.005) {
      comparison <- c(comparison, list(strsplit(pval_delta_df[pval_delta_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '**')
    }else if(pval_adj[i] < 0.0005) {
      comparison <- c(comparison, list(strsplit(pval_delta_df[pval_delta_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '***')
    }
  }
  
  # Generate the boxplot with significance annotations
  p[[count]] <- ggplot(df_all, aes(x = cluster_label, y = target, fill=cluster_label)) +
                geom_violin() +
                scale_fill_brewer(palette = "Blues") +
                geom_boxplot(outlier.shape = NA, width = .05, fill='white') +
                stat_summary(fun=match.fun(mean), geom="point", colour="red", alpha=0.7) +
                geom_signif(annotation=annotation,
                            comparisons = comparison, 
                            map_signif_level = TRUE, 
                            step_increase = 0.12,
                            ) + 
                scale_x_discrete(limits =  c('control','cluster0', 'cluster1')) +
                ylab(target) +
                
                theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  count <- count + 1
  # Print the subplot
}
plt <- do.call(grid.arrange, p)
ggsave(paste0(img_save_dir, '/', atlas, '/', 'plot','/',title, '_', year, '_delta_ttest.png'), plt, width = 18, height = 15, limitsize = FALSE,dpi=700)

```


## ==== CBCL DSM scale ==== ##
```{r cars}
title = 'CBCLDSM'
target_list = c("cbcl_dsm_depression","cbcl_dsm_anxiety","cbcl_dsm_somatic","cbcl_dsm_adhd","cbcl_dsm_opposit","cbcl_dsm_conduct")
pval_df <- read.csv(paste0(pval_save_dir, '/', atlas, '/', title, '_', year, '_ttest.csv'))
pval_delta_df = read.csv(paste0(pval_save_dir, '/', atlas, '/', title, '_', year, '_delta_ttest.csv'))

### Raw score
# Create a grid for subplots
p <- list()
count <- 1

# Loop over target variables
for (target in target_list) {
  # Data preprocess
  # Control
  df_control <- na.omit(pheno_control[, target])
  df_control <- data.frame(target = df_control, cluster_label = 'control')
  
  # Case
  df_case <- na.omit(pheno_case[, c('cluster_label', target)])
  colnames(df_case) <- c('cluster_label', 'target')
  df_case$cluster_label <- paste0('cluster', df_case$cluster_label)
  
  # Combine data
  df_all <- rbind(df_control, df_case)
  
  # P-value annotation
  
  pval_adj <- pval_df[pval_df$variables == target, ]$p_value_BONF
  comparison <- list()
  annotation <- c()
  
  for (i in 1:length(pval_adj)) {
    if (pval_adj[i] < 0.05) {
      comparison <- c(comparison, list(strsplit(pval_df[pval_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '*')
    }else if(pval_adj[i] < 0.005) {
      comparison <- c(comparison, list(strsplit(pval_df[pval_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '**')
    }else if(pval_adj[i] < 0.0005) {
      comparison <- c(comparison, list(strsplit(pval_df[pval_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '***')
    }
  }
  
  
  # Generate the boxplot with significance annotations
  p[[count]] <- ggplot(df_all, aes(x = cluster_label, y = target, fill=cluster_label)) +
                geom_violin() +
                scale_fill_brewer(palette = "Blues") +
                geom_boxplot(outlier.shape = NA, width = .05, fill='white') +
                stat_summary(fun=match.fun(mean), geom="point", colour="red", alpha=0.7) +
                geom_signif(annotation=annotation,
                            comparisons = comparison, 
                            map_signif_level = TRUE, 
                            step_increase = 0.12,
                            ) + 
                scale_x_discrete(limits =  c('control','cluster0', 'cluster1')) +
                ylab(target) + 
                
                theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  count <- count + 1
  # Print the subplot
}
plt <- do.call(grid.arrange, p)
ggsave(paste0(img_save_dir, '/', atlas, '/', 'plot','/',title, '_', year, '_ttest.png'), plt, width = 18, height = 15, limitsize = FALSE,dpi=700)


### Delta score
# Create a grid for subplots
p <- list()
count <- 1

# Loop over target variables
for (target in target_list) {
  # Data preprocess
  # Control
  df_control_baseline <- na.omit(pheno_delta_control[pheno_delta_control$eventname=='baseline_year_1_arm_1', c('subjectkey',target)])
  colnames(df_control_baseline) <- c('subjectkey', 'target_baseline')
  if (year == 'after1y'){
    df_control_followup <- na.omit(pheno_delta_control[pheno_delta_control$eventname=='1_year_follow_up_y_arm_1', c('subjectkey', target)])
  } else if (year == 'after2y'){
    df_control_followup <- na.omit(pheno_delta_control[pheno_delta_control$eventname=='2_year_follow_up_y_arm_1', c('subjectkey', target)])
  }
  colnames(df_control_followup ) <- c('subjectkey', 'target_followup')
  df_control_delta <- merge(df_control_baseline, df_control_followup, by='subjectkey')
  df_control_delta[, 'target'] <- df_control_delta[, 'target_followup'] - df_control_delta[,'target_baseline']
  df_control <- data.frame(target = df_control_delta[, 'target'], cluster_label = 'control')
  
  # Case
  df_case_baseline <- na.omit(pheno_delta_case[pheno_delta_case$eventname=='baseline_year_1_arm_1', c('subjectkey', target)])
  colnames(df_case_baseline) <- c('subjectkey','target_baseline')
  if (year == 'after1y'){
    df_case_followup <- na.omit(pheno_delta_case[pheno_delta_case$eventname=='1_year_follow_up_y_arm_1', c('subjectkey', 'cluster_label', target)])
  } else if (year == 'after2y'){
    df_case_followup <- na.omit(pheno_delta_case[pheno_delta_case$eventname=='2_year_follow_up_y_arm_1', c('subjectkey', 'cluster_label', target)])
  }
  colnames(df_case_followup) <- c('subjectkey', 'cluster_label', 'target_followup')
  df_case_delta <- merge(df_case_baseline, df_case_followup, by='subjectkey')
  df_case_delta[, 'target'] <-  df_case_delta[, 'target_followup'] - df_case_delta[,'target_baseline']
  df_case = df_case_delta[, c('target', 'cluster_label')]
  df_case$cluster_label <- paste0('cluster', df_case$cluster_label)
  
  # Combine data
  df_all <- rbind(df_control, df_case)
  
  # P-value annotation
  
  pval_adj <- pval_delta_df[pval_delta_df$variables == target, ]$p_value_BONF
  comparison <- list()
  annotation <- c()
  
  for (i in 1:length(pval_adj)) {
    if (pval_adj[i] < 0.05) {
      comparison <- c(comparison, list(strsplit(pval_delta_df[pval_delta_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '*')
    }else if(pval_adj[i] < 0.005) {
      comparison <- c(comparison, list(strsplit(pval_delta_df[pval_delta_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '**')
    }else if(pval_adj[i] < 0.0005) {
      comparison <- c(comparison, list(strsplit(pval_delta_df[pval_delta_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '***')
    }
  }
  
  
  # Generate the boxplot with significance annotations
  p[[count]] <- ggplot(df_all, aes(x = cluster_label, y = target, fill=cluster_label)) +
                geom_violin() +
                scale_fill_brewer(palette = "Blues") +
                geom_boxplot(outlier.shape = NA, width = .05, fill='white') +
                stat_summary(fun=match.fun(mean), geom="point", colour="red", alpha=0.7) +
                geom_signif(annotation=annotation,
                            comparisons = comparison, 
                            map_signif_level = TRUE, 
                            step_increase = 0.12,
                            ) + 
                scale_x_discrete(limits =  c('control','cluster0', 'cluster1')) +
                ylab(target) + 
                
                theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  count <- count + 1
  # Print the subplot
}
plt <- do.call(grid.arrange, p)
ggsave(paste0(img_save_dir, '/', atlas, '/', 'plot','/',title, '_', year, '_delta_ttest.png'), plt, width = 18, height = 15, limitsize = FALSE,dpi=700)

```


## ==== CBCL Scale2007==== ##
```{r cars}
title = 'CBCL2007'
target_list = c("cbcl_sct"	,"cbcl_ocd","cbcl_stress")
pval_df <- read.csv(paste0(pval_save_dir, '/', atlas, '/', title, '_', year, '_ttest.csv'))
pval_delta_df = read.csv(paste0(pval_save_dir, '/', atlas, '/', title, '_', year, '_delta_ttest.csv'))

### Raw score
# Create a grid for subplots
p <- list()
count <- 1

# Loop over target variables
for (target in target_list) {
  # Data preprocess
  # Control
  df_control <- na.omit(pheno_control[, target])
  df_control <- data.frame(target = df_control, cluster_label = 'control')
  
  # Case
  df_case <- na.omit(pheno_case[, c('cluster_label', target)])
  colnames(df_case) <- c('cluster_label', 'target')
  df_case$cluster_label <- paste0('cluster', df_case$cluster_label)
  
  # Combine data
  df_all <- rbind(df_control, df_case)
  
  # P-value annotation
  
  pval_adj <- pval_df[pval_df$variables == target, ]$p_value_BONF
  comparison <- list()
  annotation <- c()
  
  for (i in 1:length(pval_adj)) {
    if (pval_adj[i] < 0.05) {
      comparison <- c(comparison, list(strsplit(pval_df[pval_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '*')
    }else if(pval_adj[i] < 0.005) {
      comparison <- c(comparison, list(strsplit(pval_df[pval_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '**')
    }else if(pval_adj[i] < 0.0005) {
      comparison <- c(comparison, list(strsplit(pval_df[pval_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '***')
    }
  }
  
  
  # Generate the boxplot with significance annotations
  p[[count]] <- ggplot(df_all, aes(x = cluster_label, y = target, fill=cluster_label)) +
                geom_violin() +
                scale_fill_brewer(palette = "Blues") +
                geom_boxplot(outlier.shape = NA, width = .05, fill='white') +
                stat_summary(fun=match.fun(mean), geom="point", colour="red", alpha=0.7) +
                geom_signif(annotation=annotation,
                            comparisons = comparison, 
                            map_signif_level = TRUE, 
                            step_increase = 0.12,
                            ) + 
                scale_x_discrete(limits =  c('control','cluster0', 'cluster1')) +
                ylab(target) + 
                
                theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  count <- count + 1
  # Print the subplot
}
plt <- do.call(grid.arrange, p)
ggsave(paste0(img_save_dir, '/', atlas, '/', 'plot','/',title, '_', year, '_ttest.png'), plt, width = 12, height = 10, limitsize = FALSE,dpi=700)


### Delta score
# Create a grid for subplots
p <- list()
count <- 1

# Loop over target variables
for (target in target_list) {
  # Data preprocess
  # Control
  df_control_baseline <- na.omit(pheno_delta_control[pheno_delta_control$eventname=='baseline_year_1_arm_1', c('subjectkey',target)])
  colnames(df_control_baseline) <- c('subjectkey', 'target_baseline')
  if (year == 'after1y'){
    df_control_followup <- na.omit(pheno_delta_control[pheno_delta_control$eventname=='1_year_follow_up_y_arm_1', c('subjectkey', target)])
  } else if (year == 'after2y'){
    df_control_followup <- na.omit(pheno_delta_control[pheno_delta_control$eventname=='2_year_follow_up_y_arm_1', c('subjectkey', target)])
  }
  colnames(df_control_followup ) <- c('subjectkey', 'target_followup')
  df_control_delta <- merge(df_control_baseline, df_control_followup, by='subjectkey')
  df_control_delta[, 'target'] <- df_control_delta[, 'target_followup'] - df_control_delta[,'target_baseline']
  df_control <- data.frame(target = df_control_delta[, 'target'], cluster_label = 'control')
  
  # Case
  df_case_baseline <- na.omit(pheno_delta_case[pheno_delta_case$eventname=='baseline_year_1_arm_1', c('subjectkey', target)])
  colnames(df_case_baseline) <- c('subjectkey','target_baseline')
  if (year == 'after1y'){
    df_case_followup <- na.omit(pheno_delta_case[pheno_delta_case$eventname=='1_year_follow_up_y_arm_1', c('subjectkey', 'cluster_label', target)])
  } else if (year == 'after2y'){
    df_case_followup <- na.omit(pheno_delta_case[pheno_delta_case$eventname=='2_year_follow_up_y_arm_1', c('subjectkey', 'cluster_label', target)])
  }
  colnames(df_case_followup) <- c('subjectkey', 'cluster_label', 'target_followup')
  df_case_delta <- merge(df_case_baseline, df_case_followup, by='subjectkey')
  df_case_delta[, 'target'] <-  df_case_delta[, 'target_followup'] - df_case_delta[,'target_baseline']
  df_case = df_case_delta[, c('target', 'cluster_label')]
  df_case$cluster_label <- paste0('cluster', df_case$cluster_label)
  
  # Combine data
  df_all <- rbind(df_control, df_case)
  
  # P-value annotation
  
  pval_adj <- pval_delta_df[pval_delta_df$variables == target, ]$p_value_BONF
  comparison <- list()
  annotation <- c()
  
  for (i in 1:length(pval_adj)) {
    if (pval_adj[i] < 0.05) {
      comparison <- c(comparison, list(strsplit(pval_delta_df[pval_delta_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '*')
    }else if(pval_adj[i] < 0.005) {
      comparison <- c(comparison, list(strsplit(pval_delta_df[pval_delta_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '**')
    }else if(pval_adj[i] < 0.0005) {
      comparison <- c(comparison, list(strsplit(pval_delta_df[pval_delta_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '***')
    }
  }
  
  
  # Generate the boxplot with significance annotations
  p[[count]] <- ggplot(df_all, aes(x = cluster_label, y = target, fill=cluster_label)) +
                geom_violin() +
                scale_fill_brewer(palette = "Blues") +
                geom_boxplot(outlier.shape = NA, width = .05, fill='white') +
                stat_summary(fun=match.fun(mean), geom="point", colour="red", alpha=0.7) +
                geom_signif(annotation=annotation,
                            comparisons = comparison, 
                            map_signif_level = TRUE, 
                            step_increase = 0.12,
                            ) + 
                scale_x_discrete(limits =  c('control','cluster0', 'cluster1')) +
                ylab(target) +
                
                theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  count <- count + 1
  # Print the subplot
}
plt <- do.call(grid.arrange, p)
ggsave(paste0(img_save_dir, '/', atlas, '/', 'plot','/',title, '_', year, '_delta_ttest.png'), plt, width = 12, height = 10, limitsize = FALSE,dpi=700)

```



## ==== Screen time main category==== ##
```{r cars}
title = 'Screentime_main'
target_list = c("screentime_wkday_y", "screentime_wkend_y", "screentime_wkday_p", "screentime_wkend_p")
pval_df <- read.csv(paste0(pval_save_dir, '/', atlas, '/', title, '_', year, '_ttest.csv'))
pval_delta_df = read.csv(paste0(pval_save_dir, '/', atlas, '/', title, '_', year, '_delta_ttest.csv'))

### Raw score
# Create a grid for subplots
p <- list()
count <- 1

# Loop over target variables
for (target in target_list) {
  # Data preprocess
  # Control
  df_control <- na.omit(pheno_control[, target])
  df_control <- data.frame(target = df_control, cluster_label = 'control')
  
  # Case
  df_case <- na.omit(pheno_case[, c('cluster_label', target)])
  colnames(df_case) <- c('cluster_label', 'target')
  df_case$cluster_label <- paste0('cluster', df_case$cluster_label)
  
  # Combine data
  df_all <- rbind(df_control, df_case)
  
  # P-value annotation
  
  pval_adj <- pval_df[pval_df$variables == target, ]$p_value_BONF
  comparison <- list()
  annotation <- c()
  
  for (i in 1:length(pval_adj)) {
    if (pval_adj[i] < 0.05) {
      comparison <- c(comparison, list(strsplit(pval_df[pval_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '*')
    }else if(pval_adj[i] < 0.005) {
      comparison <- c(comparison, list(strsplit(pval_df[pval_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '**')
    }else if(pval_adj[i] < 0.0005) {
      comparison <- c(comparison, list(strsplit(pval_df[pval_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '***')
    }
  }
  
  
  # Generate the boxplot with significance annotations
  p[[count]] <- ggplot(df_all, aes(x = cluster_label, y = target, fill=cluster_label)) +
                geom_violin() +
                scale_fill_brewer(palette = "Blues") +
                geom_boxplot(outlier.shape = NA, width = .05, fill='white') +
                stat_summary(fun=match.fun(mean), geom="point", colour="red", alpha=0.7) +
                geom_signif(annotation=annotation,
                            comparisons = comparison, 
                            map_signif_level = TRUE, 
                            step_increase = 0.12,
                            ) + 
                scale_x_discrete(limits =  c('control','cluster0', 'cluster1')) +
                ggtitle(target) + 
                
                theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  count <- count + 1
  # Print the subplot
}
plt <- do.call(grid.arrange, p)
ggsave(paste0(img_save_dir, '/', atlas, '/', 'plot','/',title, '_', year, '_ttest.png'), plt, width = 36, height = 24, limitsize = FALSE,dpi=700)


### Delta score
# Create a grid for subplots
p <- list()
count <- 1

# Loop over target variables
for (target in target_list) {
  # Data preprocess
  # Control
  df_control_baseline <- na.omit(pheno_delta_control[pheno_delta_control$eventname=='baseline_year_1_arm_1', c('subjectkey',target)])
  colnames(df_control_baseline) <- c('subjectkey', 'target_baseline')
  if (year == 'after1y'){
    df_control_followup <- na.omit(pheno_delta_control[pheno_delta_control$eventname=='1_year_follow_up_y_arm_1', c('subjectkey', target)])
  } else if (year == 'after2y'){
    df_control_followup <- na.omit(pheno_delta_control[pheno_delta_control$eventname=='2_year_follow_up_y_arm_1', c('subjectkey', target)])
  }
  colnames(df_control_followup ) <- c('subjectkey', 'target_followup')
  df_control_delta <- merge(df_control_baseline, df_control_followup, by='subjectkey')
  df_control_delta[, 'target'] <- df_control_delta[, 'target_followup'] - df_control_delta[,'target_baseline']
  df_control <- data.frame(target = df_control_delta[, 'target'], cluster_label = 'control')
  
  # Case
  df_case_baseline <- na.omit(pheno_delta_case[pheno_delta_case$eventname=='baseline_year_1_arm_1', c('subjectkey', target)])
  colnames(df_case_baseline) <- c('subjectkey','target_baseline')
  if (year == 'after1y'){
    df_case_followup <- na.omit(pheno_delta_case[pheno_delta_case$eventname=='1_year_follow_up_y_arm_1', c('subjectkey', 'cluster_label', target)])
  } else if (year == 'after2y'){
    df_case_followup <- na.omit(pheno_delta_case[pheno_delta_case$eventname=='2_year_follow_up_y_arm_1', c('subjectkey', 'cluster_label', target)])
  }
  colnames(df_case_followup) <- c('subjectkey', 'cluster_label', 'target_followup')
  df_case_delta <- merge(df_case_baseline, df_case_followup, by='subjectkey')
  df_case_delta[, 'target'] <-  df_case_delta[, 'target_followup'] - df_case_delta[,'target_baseline']
  df_case = df_case_delta[, c('target', 'cluster_label')]
  df_case$cluster_label <- paste0('cluster', df_case$cluster_label)
  
  # Combine data
  df_all <- rbind(df_control, df_case)
  
  # P-value annotation
  
  pval_adj <- pval_delta_df[pval_delta_df$variables == target, ]$p_value_BONF
  comparison <- list()
  annotation <- c()
  
  for (i in 1:length(pval_adj)) {
    if (pval_adj[i] < 0.05) {
      comparison <- c(comparison, list(strsplit(pval_delta_df[pval_delta_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '*')
    }else if(pval_adj[i] < 0.005) {
      comparison <- c(comparison, list(strsplit(pval_delta_df[pval_delta_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '**')
    }else if(pval_adj[i] < 0.0005) {
      comparison <- c(comparison, list(strsplit(pval_delta_df[pval_delta_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '***')
    }
  }
  
  
  # Generate the boxplot with significance annotations
  p[[count]] <- ggplot(df_all, aes(x = cluster_label, y = target, fill=cluster_label)) +
                geom_violin() +
                scale_fill_brewer(palette = "Blues") +
                geom_boxplot(outlier.shape = NA, width = .05, fill='white') +
                stat_summary(fun=match.fun(mean), geom="point", colour="red", alpha=0.7) +
                geom_signif(annotation=annotation,
                            comparisons = comparison, 
                            map_signif_level = TRUE, 
                            step_increase = 0.12,
                            ) + 
                scale_x_discrete(limits =  c('control','cluster0', 'cluster1')) +
                ggtitle(target) + 
                
                theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  count <- count + 1
  # Print the subplot
}
plt <- do.call(grid.arrange, p)
ggsave(paste0(img_save_dir, '/', atlas, '/', 'plot','/',title, '_', year, '_delta_ttest.png'), plt, width = 36, height = 24, limitsize = FALSE,dpi=700)

```



## ==== Screen time sub category==== ##
```{r cars}
title = 'Screentime_sub'
target_list = c("screentime_wkday_tv","screentime_wkday_videos",	"screentime_wkday_games","screentime_wkday_texting","screentime_wkday_sns", "screentime_wkday_videochat", "screentime_wkend_tv", "screentime_wkend_videos", "screentime_wkend_games", "screentime_wkend_texting", "screentime_wkend_sns", "screentime_wkend_videochat", "screentime_maturegames", "screentime_rmovies")
pval_df <- read.csv(paste0(pval_save_dir, '/', atlas, '/', title, '_', year, '_ttest.csv'))
pval_delta_df = read.csv(paste0(pval_save_dir, '/', atlas, '/', title, '_', year, '_delta_ttest.csv'))

### Raw score
# Create a grid for subplots
p <- list()
count <- 1

# Loop over target variables
for (target in target_list) {
  # Data preprocess
  # Control
  df_control <- na.omit(pheno_control[, target])
  df_control <- data.frame(target = df_control, cluster_label = 'control')
  
  # Case
  df_case <- na.omit(pheno_case[, c('cluster_label', target)])
  colnames(df_case) <- c('cluster_label', 'target')
  df_case$cluster_label <- paste0('cluster', df_case$cluster_label)
  
  # Combine data
  df_all <- rbind(df_control, df_case)
  
  # P-value annotation
  
  pval_adj <- pval_df[pval_df$variables == target, ]$p_value_BONF
  comparison <- list()
  annotation <- c()
  
  for (i in 1:length(pval_adj)) {
    if (pval_adj[i] < 0.05) {
      comparison <- c(comparison, list(strsplit(pval_df[pval_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '*')
    }else if(pval_adj[i] < 0.005) {
      comparison <- c(comparison, list(strsplit(pval_df[pval_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '**')
    }else if(pval_adj[i] < 0.0005) {
      comparison <- c(comparison, list(strsplit(pval_df[pval_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '***')
    }
  }
  
  
  # Generate the boxplot with significance annotations
  p[[count]] <- ggplot(df_all, aes(x = cluster_label, y = target, fill=cluster_label)) +
                geom_violin() +
                scale_fill_brewer(palette = "Blues") +
                geom_boxplot(outlier.shape = NA, width = .05, fill='white') +
                stat_summary(fun=match.fun(mean), geom="point", colour="red", alpha=0.7) +
                geom_signif(annotation=annotation,
                            comparisons = comparison, 
                            map_signif_level = TRUE, 
                            step_increase = 0.12,
                            ) + 
                scale_x_discrete(limits =  c('control','cluster0', 'cluster1')) +
                ggtitle(target) + 
                
                theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  count <- count + 1
  # Print the subplot
}
plt <- do.call(grid.arrange, p)
ggsave(paste0(img_save_dir, '/', atlas, '/', 'plot','/',title, '_', year, '_ttest.png'), plt, width = 36, height = 24, limitsize = FALSE,dpi=700)


### Delta score
# Create a grid for subplots
p <- list()
count <- 1

# Loop over target variables
for (target in target_list) {
  # Data preprocess
  # Control
  df_control_baseline <- na.omit(pheno_delta_control[pheno_delta_control$eventname=='baseline_year_1_arm_1', c('subjectkey',target)])
  colnames(df_control_baseline) <- c('subjectkey', 'target_baseline')
  if (year == 'after1y'){
    df_control_followup <- na.omit(pheno_delta_control[pheno_delta_control$eventname=='1_year_follow_up_y_arm_1', c('subjectkey', target)])
  } else if (year == 'after2y'){
    df_control_followup <- na.omit(pheno_delta_control[pheno_delta_control$eventname=='2_year_follow_up_y_arm_1', c('subjectkey', target)])
  }
  colnames(df_control_followup ) <- c('subjectkey', 'target_followup')
  df_control_delta <- merge(df_control_baseline, df_control_followup, by='subjectkey')
  df_control_delta[, 'target'] <- df_control_delta[, 'target_followup'] - df_control_delta[,'target_baseline']
  df_control <- data.frame(target = df_control_delta[, 'target'], cluster_label = 'control')
  
  # Case
  df_case_baseline <- na.omit(pheno_delta_case[pheno_delta_case$eventname=='baseline_year_1_arm_1', c('subjectkey', target)])
  colnames(df_case_baseline) <- c('subjectkey','target_baseline')
  if (year == 'after1y'){
    df_case_followup <- na.omit(pheno_delta_case[pheno_delta_case$eventname=='1_year_follow_up_y_arm_1', c('subjectkey', 'cluster_label', target)])
  } else if (year == 'after2y'){
    df_case_followup <- na.omit(pheno_delta_case[pheno_delta_case$eventname=='2_year_follow_up_y_arm_1', c('subjectkey', 'cluster_label', target)])
  }
  colnames(df_case_followup) <- c('subjectkey', 'cluster_label', 'target_followup')
  df_case_delta <- merge(df_case_baseline, df_case_followup, by='subjectkey')
  df_case_delta[, 'target'] <-  df_case_delta[, 'target_followup'] - df_case_delta[,'target_baseline']
  df_case = df_case_delta[, c('target', 'cluster_label')]
  df_case$cluster_label <- paste0('cluster', df_case$cluster_label)
  
  # Combine data
  df_all <- rbind(df_control, df_case)
  
  # P-value annotation
  
  pval_adj <- pval_delta_df[pval_delta_df$variables == target, ]$p_value_BONF
  comparison <- list()
  annotation <- c()
  
  for (i in 1:length(pval_adj)) {
    if (pval_adj[i] < 0.05) {
      comparison <- c(comparison, list(strsplit(pval_delta_df[pval_delta_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '*')
    }else if(pval_adj[i] < 0.005) {
      comparison <- c(comparison, list(strsplit(pval_delta_df[pval_delta_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '**')
    }else if(pval_adj[i] < 0.0005) {
      comparison <- c(comparison, list(strsplit(pval_delta_df[pval_delta_df$variables == target, ]$test[i], split = '-')[[1]]))
      annotation <- append(annotation, '***')
    }
  }
  
  
  # Generate the boxplot with significance annotations
  p[[count]] <- ggplot(df_all, aes(x = cluster_label, y = target, fill=cluster_label)) +
                geom_violin() +
                scale_fill_brewer(palette = "Blues") +
                geom_boxplot(outlier.shape = NA, width = .05, fill='white') +
                stat_summary(fun=match.fun(mean), geom="point", colour="red", alpha=0.7) +
                geom_signif(annotation=annotation,
                            comparisons = comparison, 
                            map_signif_level = TRUE, 
                            step_increase = 0.12,
                            ) + 
                scale_x_discrete(limits =  c('control','cluster0', 'cluster1')) +
                ggtitle(target) + 
                
                theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
  count <- count + 1
  # Print the subplot
}
plt <- do.call(grid.arrange, p)
ggsave(paste0(img_save_dir, '/', atlas, '/', 'plot','/',title, '_', year, '_delta_ttest.png'), plt, width = 36, height = 24, limitsize = FALSE,dpi=700)

```